### ISSUE TITLE
duplicate geometries

### ISSUE THREAD

**Issue by gregmaya** [OpenDigitalWorks/CatchmentAnalyser#6]
When running a catchment analysis from multiple points the network outcome brings up duplicate features. For visualization purposes this is not a big issue but I thought you might be interested to know.

All the best !
G.

**Comment by laurensversluis** [comment]
Do you mean the segment output or the polygon output? Are you using the latest version?

**Comment by gregmaya** [comment]
Hi Laurens !

 

I meant that there are duplicate lines in the segment output when you generate catchments from multiple origins (obviously when they overlap)

For that I’ve been using the following script that run super quick and does a pretty good job:

 

WITH unique_geom (dup_id, id, geom) as

(SELECT row_number() OVER (PARTITION BY geom) as dup_id , id, geom FROM "####".xxxxxx)

DELETE FROM "####".xxxxxx

WHERE id IN (SELECT id FROM unique_geom WHERE dup_id > 1);

 

And yes I’m using the latest version!

 

Hope it helps,

 

G

**Comment by jorgegil** [comment]
This happens with all origins, also with non overlapping catchments.
It creates 2 duplicates, and not more than that as would be expected if the problem was related to overlaps.

**Comment by jorgegil** [comment]
The current algorithm to create the catchment network constructs it from end points (nodes in the graph). I suspect every line gets duplicated because this is an undirected network and every arc can be approached from either end and appears twice in the search tree.

We have to revise carefully the whole network analysis algorithm to be able to fix this.

**Comment by jorgegil** [comment]
Done a simple fix.
When constructing the network the algorithm stores the start and end point id, BUT always stores the lowest id number first. This way, because it is undirected, duplicate arcs will have an identical pair of start and end ids, even if the geometry is reversed.
Then we can check for these duplicates, instead of trying to match geometries and lengths (can be error prone).
