### ISSUE TITLE
some lines disappear from the result with some networks

### ISSUE THREAD

**Issue by Anafi** [OpenDigitalWorks/CatchmentAnalyser#7]

**Comment by jorgegil** [comment]
The tool tries to identify and remove duplicates based on line length. I can imagine this happens if there are lines with duplicate lengths.
The current algorithm must be revised to address this approach. Might also be related to #6.

**Comment by jorgegil** [comment]
Since #6 is fixed, it's possible that this one is fixed as well.

Please note, the tool currently only includes in catchment segments that are entirely within distance (both start and end). It's possible that some lines look like they would be but are not based on this restriction.
Also, lines might be within the polygon but not in catchment. The polygon is only an approximation, and the other alternative would be a small buffer.

**Comment by jorgegil** [comment]
With the changes to issue #14 it's likely that this problem is not noticed any more. The network output is now more inclusive, and the polygon output accurate.

I'll close for now as I haven't observed this in tests.
Can reopen if the issue pops-up with a clear pattern: what lines and what networks.
